export CURRENT_TIMESTAMP
CURRENT_TIMESTAMP="$(date +%A-%Y-%m-%d-%T)"

export LOGDIR_FULL_PATH
LOGDIR_FULL_PATH="$(realpath ../logs)"

export LOGFILENAME
LOGFILENAME="${LOGDIR_FULL_PATH}/$0.${CURRENT_TIMESTAMP}.$$"